# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3f3edb19abd6e3d33fc2fb0758b0ec28c5cc17f1b4e30fa6e671f16b57172622b9abbaab901e1b9bf54fc07ab795605c343aa6c02cae15b712e6b7e56329861

test:
  secret_key_base: d7b2f38420eee50a71141046bf9bf06646686ef1bde9cbeafca4327eb01030c6a2f9f27579ad20242da791f3abd94ce3053490c54ccb0fce7244ecca90223112

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
